#https://github.com/actions/setup-node
#https://docs.github.com/en/actions/quickstart
#https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
# https://kontent.ai/blog/how-to-trigger-github-action-using-webhook-with-no-code/
name: Build and Deploy

on:
  # pull:
  #   branches: master
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - run: |
          echo "PRISMIC_REPO_NAME=${{ secrets.PRISMIC_REPO_NAME }}" > .env.production
          echo "PRISMIC_CUSTOM_TYPES_API_TOKEN=${{ secrets.PRISMIC_CUSTOM_TYPES_API_TOKEN }}" >> .env.production

      - name: Build
        run: npm run build

      - name: Verify build
        run: ls -la public

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          - aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          - aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          - aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to S3
        run: aws s3 sync public s3://${{ secrets.AWS_BUCKET_NAME }} --delete
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"